### ISSUE TITLE
Absorbs bar

### ISSUE THREAD

**Issue by LuckyDjuk** [nexiuhm/HealingSim-ES6#28]
Broken

**Comment by nexiuhm** [comment]
This is actually a very annyoing problem because it seems to hard to do in a correct and clean way (which it wasnt before)  Basicly you want the x value of the absorb bar to update everytime the health moves, so that the absorb-bar always starts at the right edge of the health. 

Seems simple enough, so why is it a issue?
Well, since the movement of the healthbar is animated using a tween ( to add smooth movemement ) the x value of the absorb bar needs to have the exact same smoothing or it will not follow correctly. Of course we can simply add the same smoothing to them both ( implemented in the unitFrame class )

Actually ..  :p as im writing this i realize it might not be such a big issue anyway, we just need to be careful to always use the same smoothing/animation speed. Helps putting it on paper i guess :p idk what i was thinking.

I tired the alternative of adding it too the game loop, so that x of absorb-bar will constatly update itself with the current healthbar width value. But it doesnt happen "fast" enough, so you can see obvious clipping. I dont think this would be a good soulution anyway, since even if the health hasnt moved it will update and render again, which will cost some cpu powah.

**Comment by nexiuhm** [comment]
Its working now, but its not perfect. I think the best possible soulution would be to anchor the absorb-bar  to "top right" of the healthbar somehow so that it will just move perfectly without bothering about manually setting its x value everytime the healthbar gets smaller or bigger. 

I'm not exactly sure how to do this atm so adding this note here as a reminder.
`Figure out how to anchor a child to a specific point on the parent, as in : child.anchor = parent_top_right`
